name: CI
on:
  pull_request:
    branches: [ "main" ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # Nodeプロジェクトの場合だけ実行
      - name: Setup Node
        if: hashFiles('**/package.json') != ''
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: "npm"

      - name: Install deps
        if: hashFiles('**/package.json') != ''
        run: npm ci

      - name: Lint
        if: hashFiles('**/package.json') != ''
        run: npm run lint --if-present

      - name: Test
        if: hashFiles('**/package.json') != ''
        run: npm test --if-present

      - name: Sanity
        run: echo "CI OK"
