name: Auto trigger CodeRabbit on bot PRs

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  trigger:
    # Dependabot / Renovate など Bot のPRだけに限定
    if: |
      github.actor == 'dependabot[bot]' ||
      github.actor == 'renovate[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Comment to trigger CodeRabbit
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: '@coderabbitai review'
